### ISSUE TITLE
Error message "No module named 'gedcom.GedcomParser'

### ISSUE THREAD

**Issue by frankbracq** [D-Jeffrey/gedcom-to-visualmap#2]
Hi

I'm getting an error when running 'python gedcomVisualGUI.py'. Have a look at attached screenshot.

Thanks in advance for your help.

Frank
![Untitled](https://user-images.githubusercontent.com/35921662/229104957-dfd83bd7-b3b3-46a8-af9c-0a42ac624c0a.jpg)

**Comment by D-Jeffrey** [comment]
Thanks @frankbracq for trying this out and testing it out.  Give 0.2.2 release a try, not sure if that will fix your issue.  I assume you have downloaded the full code base with the sub-directories, including gedcom directory and the one file.  I assume your experience is going to be like the Linux experience.  Your experience should be similar to the snap.

Looking for the feedback - good, bad or otherwise

**Comment by D-Jeffrey** [comment]
@frankbracq - new release.  It changes the location of the imports so go with that one instead [release 2.3](https://github.com/D-Jeffrey/gedcom-to-visualmap/releases/tag/v0.2.3)

**Comment by D-Jeffrey** [comment]
Assumed fixed in 2.3+
